spring:
  datasource:
    url: ${DB_JOB_URL}
    username: ${DB_JOB_USERNAME}
    password: ${DB_JOB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0        # ← FIX : baseline à 0 pour que V1 soit exécuté
    validate-on-migrate: true

  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
      password: ${REDIS_TOKEN}
      ssl:
        enabled: true       # OBLIGATOIRE pour Upstash (TLS sur port 6380)
      timeout: 2000ms

# CORRECTION : "skill" est à la RACINE, PAS sous "spring:"
skill:
  extractor:
    provider: ${SKILL_PROVIDER:huggingface}
    hf:
      token: ${HF_TOKEN:}
      model: Davlan/bert-base-multilingual-cased-ner-hrl
    ollama:
      url: ${OLLAMA_URL:http://localhost:11434}
      model: gemma2:2b

jobsapi:
  base-url: ${JOBSAPI_BASE_URL}
  key: ${JOBAPI_KEY}

jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

feign:
  client:
    config:
      default:
        loggerLevel: NONE