server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.kqbquwbzbzxfwbfiayxy
    password: "MiFkT#DQVj+5H,_"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: assiyasousou1@gmail.com
    password: "gtsl lqnn cprz osgo"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

internal:
  security:
    gateway-secret: 2RD15mg+lZB1frvOkiaUN9Ycp98o5VMHKHFsfuL4U6U=

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

app:
  password-reset-token-expiration: 3600000
  frontend-url: http://localhost:3000
  max-failed-login-attempts: 5

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    org.springframework.security: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs