spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:

            # ── Job Service ────────────────────────────────────────────
            - id: job-service
              uri: lb://job-service
              predicates:
                - Path=/api/job/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: job-service-cb
                    fallbackUri: forward:/fallback/job

            # ── CV Service ─────────────────────────────────────────────
            - id: cv-service
              uri: lb://cv-service
              predicates:
                - Path=/api/cv/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: cv-service-cb
                    fallbackUri: forward:/fallback/cv

            # ── Auth Service ─────────────────────────────────────────────
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**, /api/tokens/**, /api/users/**
              filters:
                - StripPrefix=0

            # ── Roadmap Service ─────────────────────────────────────────────
            - id: roadmap-service
              uri: lb://roadmap-service
              predicates:
                - Path=/api/roadmap/**
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://localhost:8090}
        username: ${ADMIN_USERNAME:admin}
        password: ${ADMIN_PASSWORD:admin}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

internal:
  security:
    gateway-secret: ${INTERNAL_GATEWAY_SECRET:2RD15mg+lZB1frvOkiaUN9Ycp98o5VMHKHFsfuL4U6U=}


resilience4j:
  circuitbreaker:
    instances:
      job-service-cb:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
      auth-service-cb:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
      cv-service-cb:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s