spring:
  application:
    name: cv-service
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  profiles:
    active: ${CONFIG_SERVER_PROFILE}
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 1000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# ─── SECURITE & JWT & API GATEWAY ────────────────────
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

internal:
  security:
    gateway-secret: ${INTERNAL_GATEWAY_SECRET:2RD15mg+lZB1frvOkiaUN9Ycp98o5VMHKHFsfuL4U6U=}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
