server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: ${CONFIG_SERVER_PROFILE:git}
  cloud:
    config:
      server:
        native:
          search-locations: file:${CONFIG_REPO_PATH}
        git:
          uri: https://github.com/ENSIAS-MEH/development-platform-bloom
          default-label: main
          search-paths: config-repo
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}

