apiVersion: v1
kind: ConfigMap
metadata:
  name: bloom-config
  namespace: bloom
data:
  CONFIG_SERVER_URL: "http://config-server:8888"
  EUREKA_URI: "http://discovery-server:8761/eureka/"
  ADMIN_SERVER_URL: "http://admin-server:8090"
  CONFIG_SERVER_PROFILE: "native"
  GEMINI_MODEL_ROADMAP: "gemini-2.0-flash"
  FRONTEND_URL: "http://bloom.local"
---
apiVersion: v1
kind: Secret
metadata:
  name: bloom-secrets
  namespace: bloom
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME"
  INTERNAL_GATEWAY_SECRET: "CHANGE_ME"

  DB_CV_URL: "jdbc:postgresql://HOST:5432/DBNAME?sslmode=require"
  DB_CV_USERNAME: "CHANGE_ME"
  DB_CV_PASSWORD: "CHANGE_ME"

  DB_JOB_URL: "jdbc:postgresql://HOST:5432/DBNAME?sslmode=require"
  DB_JOB_USERNAME: "CHANGE_ME"
  DB_JOB_PASSWORD: "CHANGE_ME"

  REDIS_URL: "rediss://default:CHANGE_ME@HOST:6379"

  GEMINI_API_KEY_CV: ""
  GEMINI_API_KEY_JOB_SKILLS: ""
  SKILL_EXTRACTOR_HF_MODEL_URL: ""
  JOBSAPI_BASE_URL: ""
  JOBAPI_KEY: ""

  DB_AUTH_URL: "jdbc:postgresql://HOST:5432/postgres?sslmode=require"
  DB_AUTH_USER: "CHANGE_ME"
  DB_AUTH_PASS: "CHANGE_ME"
  MAIL_HOST: "CHANGE_ME"
  MAIL_USER: "CHANGE_ME"
  MAIL_PASS: "CHANGE_ME"

  DB_ROADMAP_URL: "jdbc:postgresql://HOST:5432/DBNAME?sslmode=require"
  DB_ROADMAP_USERNAME: "CHANGE_ME"
  DB_ROADMAP_PASSWORD: "CHANGE_ME"
  GEMINI_API_KEY_ROADMAP: ""
