name: Bloom CD — admin-server

on:
  push:
    branches: [ main ]
    paths:
      - 'infrastructure/admin-server/**'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/cd-reusable.yaml
    secrets: inherit
    with:
      image: bloom-admin-server
      context: infrastructure/admin-server
      deployment: admin-server
